language: R
sudo: false
cache:
- directories:
  - $HOME/.ccache

warnings_are_errors: false
env:
- _R_CHECK_FORCE_SUGGESTS_=false

before_install:
  - mkdir -p ~/.R; ( echo 'CC := ccache $(CC)'; echo 'CXX := ccache $(CXX)'; echo 'MAKEFLAGS := -j 2' ) > ~/.R/Makevars

before_script:
  - psql -c 'create database test;' -U postgres
  - mkdir -p ~/.R; ( echo 'CC := ccache $(CC)'; echo 'CXX := ccache $(CXX)'; echo 'MAKEFLAGS := -j 2' ) > ~/.R/Makevars

after_success:
- Rscript -e 'covr::codecov()'
