# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel

warnings_are_errors: false
env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=false

before_install:
  - Rscript -e "install.packages('git2r')"
  - export MAKEFLAGS="-j 2"
  - Rscript -e "install.packages('devtools')"
  - Rscript -e "devtools::install_github('hadley/devtools')"
  - Rscript -e "devtools::install_deps(dependencies = TRUE)"

before_script:
  - psql -c 'create database test;' -U postgres

after_success:
- Rscript -e 'covr::codecov()'
