language: R
sudo: false
cache:
- directories:
  - $HOME/.ccache

warnings_are_errors: false
env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - PATH=/usr/lib/ccache:$PATH

before_script:
  - psql -c 'create database test;' -U postgres

after_success:
- Rscript -e 'covr::codecov()'
