language: R
sudo: false
cache:
- packages
- directories:
  - $HOME/.ccache

warnings_are_errors: false
env:
- _R_CHECK_FORCE_SUGGESTS_=false

before_install:
  - mkdir -p ~/.R; ( echo "CC := ccache gcc $(CC)"; echo "CXX := ccache g++ $(CXX)"; echo "MAKEFLAGS := -j 2" ) > ~/.R/Makevars

before_script:
  - psql -c 'create database test;' -U postgres
  - mkdir -p ~/.R; ( echo "CC := ccache gcc $(CC)"; echo "CXX := ccache g++ $(CXX)"; echo "MAKEFLAGS := -j 2" ) > ~/.R/Makevars

after_success:
- Rscript -e 'covr::codecov()'
