language: R
sudo: false
cache: packages

warnings_are_errors: false
env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=false

r_github_packages: hadley/dtplyr

before_install:
  - export MAKEFLAGS="-j 2"

before_script:
  - psql -c 'create database test;' -U postgres

after_success:
- Rscript -e 'covr::codecov()'
