language: R
sudo: false
cache:
- packages
- directories:
  - $HOME/.ccache

warnings_are_errors: false
env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false

before_script:
  - export PATH=/usr/lib/ccache:$PATH
  - psql -c 'create database test;' -U postgres

after_success:
- Rscript -e 'covr::codecov()'
